//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Grammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule([NotNull] GrammarParser.RuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule([NotNull] GrammarParser.RuleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MaxOf</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaxOf([NotNull] GrammarParser.MaxOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MaxOf</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaxOf([NotNull] GrammarParser.MaxOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NegativeNumber</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegativeNumber([NotNull] GrammarParser.NegativeNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NegativeNumber</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegativeNumber([NotNull] GrammarParser.NegativeNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Wrong</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWrong([NotNull] GrammarParser.WrongContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Wrong</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWrong([NotNull] GrammarParser.WrongContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] GrammarParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] GrammarParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditionSubtraction</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionSubtraction([NotNull] GrammarParser.AdditionSubtractionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditionSubtraction</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionSubtraction([NotNull] GrammarParser.AdditionSubtractionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MinOf</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinOf([NotNull] GrammarParser.MinOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MinOf</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinOf([NotNull] GrammarParser.MinOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InPower</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInPower([NotNull] GrammarParser.InPowerContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InPower</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInPower([NotNull] GrammarParser.InPowerContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InBrackets</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInBrackets([NotNull] GrammarParser.InBracketsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InBrackets</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInBrackets([NotNull] GrammarParser.InBracketsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicationDivision</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicationDivision([NotNull] GrammarParser.MultiplicationDivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicationDivision</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicationDivision([NotNull] GrammarParser.MultiplicationDivisionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cell</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCell([NotNull] GrammarParser.CellContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cell</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCell([NotNull] GrammarParser.CellContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OnDiv</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnDiv([NotNull] GrammarParser.OnDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OnDiv</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnDiv([NotNull] GrammarParser.OnDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OnModulo</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnModulo([NotNull] GrammarParser.OnModuloContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OnModulo</c>
	/// labeled alternative in <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnModulo([NotNull] GrammarParser.OnModuloContext context);
}
